image:
  file: .gitpod.dockerfile

tasks:
    - before: nvm install 18.18.0 && nvm use 18.18.0
      init: npm install
      command: npm run start-server

ports:
    - port: 8080
      onOpen: open-preview
